//*
// Generated by go-doudou v2.0.4.
// Don't edit!
//
// Version No.: v20230115

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: transport/grpc/prom.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLabelLabelNameValuesRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Start timestamp. Optional.
	//
	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// End timestamp. Optional.
	//
	End string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// Repeated series selector argument that selects the series from which to read the label values. Optional.
	//
	Match []string `protobuf:"bytes,3,rep,name=match,proto3" json:"match,omitempty"`
	// Label name
	//
	// Example: "/label/job/values"
	//
	// required
	LabelName string `protobuf:"bytes,4,opt,name=labelName,proto3" json:"labelName,omitempty"`
}

func (x *GetLabelLabelNameValuesRpcRequest) Reset() {
	*x = GetLabelLabelNameValuesRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabelLabelNameValuesRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelLabelNameValuesRpcRequest) ProtoMessage() {}

func (x *GetLabelLabelNameValuesRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelLabelNameValuesRpcRequest.ProtoReflect.Descriptor instead.
func (*GetLabelLabelNameValuesRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{0}
}

func (x *GetLabelLabelNameValuesRpcRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetLabelLabelNameValuesRpcRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetLabelLabelNameValuesRpcRequest) GetMatch() []string {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *GetLabelLabelNameValuesRpcRequest) GetLabelName() string {
	if x != nil {
		return x.LabelName
	}
	return ""
}

type GetLabelLabelNameValuesRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetLabelLabelNameValuesRpcResponse) Reset() {
	*x = GetLabelLabelNameValuesRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabelLabelNameValuesRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelLabelNameValuesRpcResponse) ProtoMessage() {}

func (x *GetLabelLabelNameValuesRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelLabelNameValuesRpcResponse.ProtoReflect.Descriptor instead.
func (*GetLabelLabelNameValuesRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{1}
}

func (x *GetLabelLabelNameValuesRpcResponse) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetLabelLabelNameValuesRpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetQueryRangeRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Prometheus expression query string.
	//
	// Example: "?query=up"
	//
	// required
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Start timestamp.
	//
	// Example: "&start=2015-07-01T20:10:30.781Z"
	//
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// End timestamp.
	//
	// Example: "&end=2015-07-01T20:11:00.781Z"
	//
	End string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// Query resolution step width in "duration" format or float number of seconds.
	//
	// Example: "&step=15s"
	//
	Step string `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	// Evaluation timeout. Optional.
	Timeout string `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *GetQueryRangeRpcRequest) Reset() {
	*x = GetQueryRangeRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueryRangeRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryRangeRpcRequest) ProtoMessage() {}

func (x *GetQueryRangeRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryRangeRpcRequest.ProtoReflect.Descriptor instead.
func (*GetQueryRangeRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{2}
}

func (x *GetQueryRangeRpcRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetQueryRangeRpcRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetQueryRangeRpcRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetQueryRangeRpcRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *GetQueryRangeRpcRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type GetQueryRangeRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *QueryData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetQueryRangeRpcResponse) Reset() {
	*x = GetQueryRangeRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueryRangeRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryRangeRpcResponse) ProtoMessage() {}

func (x *GetQueryRangeRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryRangeRpcResponse.ProtoReflect.Descriptor instead.
func (*GetQueryRangeRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{3}
}

func (x *GetQueryRangeRpcResponse) GetData() *QueryData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetQueryRangeRpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetQueryRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Prometheus expression query string.
	//
	// Example: "?query=up"
	//
	// required
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Evaluation timestamp. Optional.
	//
	// The current server time is used if the "time" parameter is omitted.
	//
	// Optional.
	Time string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Evaluation timeout. Optional.
	Timeout string `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *GetQueryRpcRequest) Reset() {
	*x = GetQueryRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueryRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryRpcRequest) ProtoMessage() {}

func (x *GetQueryRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryRpcRequest.ProtoReflect.Descriptor instead.
func (*GetQueryRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{4}
}

func (x *GetQueryRpcRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetQueryRpcRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *GetQueryRpcRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type GetQueryRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *QueryData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetQueryRpcResponse) Reset() {
	*x = GetQueryRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueryRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryRpcResponse) ProtoMessage() {}

func (x *GetQueryRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryRpcResponse.ProtoReflect.Descriptor instead.
func (*GetQueryRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{5}
}

func (x *GetQueryRpcResponse) GetData() *QueryData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetQueryRpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     *anypb.Any `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ResultType string     `protobuf:"bytes,2,opt,name=resultType,proto3" json:"resultType,omitempty"`
}

func (x *QueryData) Reset() {
	*x = QueryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryData) ProtoMessage() {}

func (x *QueryData) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryData.ProtoReflect.Descriptor instead.
func (*QueryData) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{6}
}

func (x *QueryData) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryData) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

type QueryRangeRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Prometheus expression query string.
	//
	// Example: "?query=up"
	//
	// required
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Start timestamp.
	//
	// Example: "&start=2015-07-01T20:10:30.781Z"
	//
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// End timestamp.
	//
	// Example: "&end=2015-07-01T20:11:00.781Z"
	//
	End string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// Query resolution step width in "duration" format or float number of seconds.
	//
	// Example: "&step=15s"
	//
	Step string `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	// Evaluation timeout. Optional.
	Timeout string `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *QueryRangeRpcRequest) Reset() {
	*x = QueryRangeRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRangeRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeRpcRequest) ProtoMessage() {}

func (x *QueryRangeRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeRpcRequest.ProtoReflect.Descriptor instead.
func (*QueryRangeRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRangeRpcRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRangeRpcRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *QueryRangeRpcRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *QueryRangeRpcRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *QueryRangeRpcRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type QueryRangeRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *QueryData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *QueryRangeRpcResponse) Reset() {
	*x = QueryRangeRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRangeRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeRpcResponse) ProtoMessage() {}

func (x *QueryRangeRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeRpcResponse.ProtoReflect.Descriptor instead.
func (*QueryRangeRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{8}
}

func (x *QueryRangeRpcResponse) GetData() *QueryData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryRangeRpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *QueryData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResponse) GetData() *QueryData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Prometheus expression query string.
	//
	// Example: "?query=up"
	//
	// required
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Evaluation timestamp. Optional.
	//
	// The current server time is used if the "time" parameter is omitted.
	//
	// Optional.
	Time string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Evaluation timeout. Optional.
	Timeout string `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *QueryRpcRequest) Reset() {
	*x = QueryRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRpcRequest) ProtoMessage() {}

func (x *QueryRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRpcRequest.ProtoReflect.Descriptor instead.
func (*QueryRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRpcRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRpcRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *QueryRpcRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type QueryRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *QueryData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *QueryRpcResponse) Reset() {
	*x = QueryRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_prom_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRpcResponse) ProtoMessage() {}

func (x *QueryRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_prom_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRpcResponse.ProtoReflect.Descriptor instead.
func (*QueryRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_prom_proto_rawDescGZIP(), []int{11}
}

func (x *QueryRpcResponse) GetData() *QueryData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryRpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_transport_grpc_prom_proto protoreflect.FileDescriptor

var file_transport_grpc_prom_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x72, 0x6f,
	0x6d, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x21,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a,
	0x22, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x85, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x57, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x58, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x52, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x59,
	0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x14, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x74, 0x65, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x54,
	0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x4c, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x55, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x4f, 0x0a, 0x10, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x6d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x9a, 0x03, 0x0a, 0x0b, 0x50,
	0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x70, 0x63, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x6d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x47, 0x65,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x52, 0x70, 0x63, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x75, 0x62, 0x69, 0x6e, 0x31, 0x39, 0x38, 0x39, 0x2f,
	0x70, 0x72, 0x6f, 0x6d, 0x71, 0x6c, 0x32, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x71, 0x6c, 0x2f,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x6d, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_grpc_prom_proto_rawDescOnce sync.Once
	file_transport_grpc_prom_proto_rawDescData = file_transport_grpc_prom_proto_rawDesc
)

func file_transport_grpc_prom_proto_rawDescGZIP() []byte {
	file_transport_grpc_prom_proto_rawDescOnce.Do(func() {
		file_transport_grpc_prom_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_grpc_prom_proto_rawDescData)
	})
	return file_transport_grpc_prom_proto_rawDescData
}

var file_transport_grpc_prom_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transport_grpc_prom_proto_goTypes = []interface{}{
	(*GetLabelLabelNameValuesRpcRequest)(nil),  // 0: prom.GetLabelLabelNameValuesRpcRequest
	(*GetLabelLabelNameValuesRpcResponse)(nil), // 1: prom.GetLabelLabelNameValuesRpcResponse
	(*GetQueryRangeRpcRequest)(nil),            // 2: prom.GetQueryRangeRpcRequest
	(*GetQueryRangeRpcResponse)(nil),           // 3: prom.GetQueryRangeRpcResponse
	(*GetQueryRpcRequest)(nil),                 // 4: prom.GetQueryRpcRequest
	(*GetQueryRpcResponse)(nil),                // 5: prom.GetQueryRpcResponse
	(*QueryData)(nil),                          // 6: prom.QueryData
	(*QueryRangeRpcRequest)(nil),               // 7: prom.QueryRangeRpcRequest
	(*QueryRangeRpcResponse)(nil),              // 8: prom.QueryRangeRpcResponse
	(*QueryResponse)(nil),                      // 9: prom.QueryResponse
	(*QueryRpcRequest)(nil),                    // 10: prom.QueryRpcRequest
	(*QueryRpcResponse)(nil),                   // 11: prom.QueryRpcResponse
	(*anypb.Any)(nil),                          // 12: google.protobuf.Any
}
var file_transport_grpc_prom_proto_depIdxs = []int32{
	6,  // 0: prom.GetQueryRangeRpcResponse.data:type_name -> prom.QueryData
	6,  // 1: prom.GetQueryRpcResponse.data:type_name -> prom.QueryData
	12, // 2: prom.QueryData.result:type_name -> google.protobuf.Any
	6,  // 3: prom.QueryRangeRpcResponse.data:type_name -> prom.QueryData
	6,  // 4: prom.QueryResponse.data:type_name -> prom.QueryData
	6,  // 5: prom.QueryRpcResponse.data:type_name -> prom.QueryData
	10, // 6: prom.PromService.QueryRpc:input_type -> prom.QueryRpcRequest
	4,  // 7: prom.PromService.GetQueryRpc:input_type -> prom.GetQueryRpcRequest
	7,  // 8: prom.PromService.QueryRangeRpc:input_type -> prom.QueryRangeRpcRequest
	2,  // 9: prom.PromService.GetQueryRangeRpc:input_type -> prom.GetQueryRangeRpcRequest
	0,  // 10: prom.PromService.GetLabelLabelNameValuesRpc:input_type -> prom.GetLabelLabelNameValuesRpcRequest
	11, // 11: prom.PromService.QueryRpc:output_type -> prom.QueryRpcResponse
	5,  // 12: prom.PromService.GetQueryRpc:output_type -> prom.GetQueryRpcResponse
	8,  // 13: prom.PromService.QueryRangeRpc:output_type -> prom.QueryRangeRpcResponse
	3,  // 14: prom.PromService.GetQueryRangeRpc:output_type -> prom.GetQueryRangeRpcResponse
	1,  // 15: prom.PromService.GetLabelLabelNameValuesRpc:output_type -> prom.GetLabelLabelNameValuesRpcResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_transport_grpc_prom_proto_init() }
func file_transport_grpc_prom_proto_init() {
	if File_transport_grpc_prom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_grpc_prom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabelLabelNameValuesRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabelLabelNameValuesRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueryRangeRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueryRangeRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueryRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueryRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRangeRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRangeRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_prom_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_grpc_prom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_prom_proto_goTypes,
		DependencyIndexes: file_transport_grpc_prom_proto_depIdxs,
		MessageInfos:      file_transport_grpc_prom_proto_msgTypes,
	}.Build()
	File_transport_grpc_prom_proto = out.File
	file_transport_grpc_prom_proto_rawDesc = nil
	file_transport_grpc_prom_proto_goTypes = nil
	file_transport_grpc_prom_proto_depIdxs = nil
}
