/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
*/
package service

import (
	"context"
	"github.com/wubin1989/promql2influxql/rpc/dto"
)

//go:generate go-doudou svc http -c
//go:generate go-doudou svc grpc

type Rpc interface {
	// You can define your service methods as your need. Below is an example.
	// You can also add annotations here like @role(admin) to add meta data to routes for 
	// implementing your own middlewares
	PageUsers(ctx context.Context, query dto.PageQuery) (data dto.PageRet, err error)
}
