/**
* Generated by go-doudou v2.0.4.
* Don't edit!
 */
package client

import (
	"context"

	"github.com/go-resty/resty/v2"
	"github.com/wubin1989/promql2influxql/applications/prom/dto"
)

type IPromClient interface {
	Query(ctx context.Context, _headers map[string]string, query string, time *string, timeout *string) (_resp *resty.Response, data dto.QueryData, status string, err error)
	GetQuery(ctx context.Context, _headers map[string]string, query string, time *string, timeout *string) (_resp *resty.Response, data dto.QueryData, status string, err error)
	Query_range(ctx context.Context, _headers map[string]string, query string, start *string, end *string, step *string, timeout *string) (_resp *resty.Response, data dto.QueryData, status string, err error)
	GetQuery_range(ctx context.Context, _headers map[string]string, query string, start *string, end *string, step *string, timeout *string) (_resp *resty.Response, data dto.QueryData, status string, err error)
	GetLabel_Label_nameValues(ctx context.Context, _headers map[string]string, start *string, end *string, match *[]string, label_name string) (_resp *resty.Response, data []string, status string, err error)
}
