global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: node
    static_configs:
      - targets: [ '192.168.98.151:9100' ]
  - job_name: "promql2influxql_promql2influxql"
    basic_auth:
      username: admin
      password: admin
    metrics_path: /go-doudou/prometheus
    static_configs:
      - targets:
          - promql2influxql_promql2influxql:9090

# Remote write configuration (for Graphite, OpenTSDB, or InfluxDB).
remote_write:
  - url: "http://promql2influxql_influxdb:8086/api/v1/prom/write?db=prometheus"