/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package config

import (
	"github.com/kelseyhightower/envconfig"
	"github.com/unionj-cloud/go-doudou/v2/toolkit/zlogger"
	"time"
)

type Config struct {
	DbConf  DbConfig
	BizConf BizConfig
}

type DbConfig struct {
	Driver  string `default:"mysql"`
	Host    string `default:"localhost"`
	Port    string `default:"3306"`
	User    string
	Passwd  string
	Schema  string
	Charset string `default:"utf8mb4"`
}

type BizConfig struct {
	AdaptorTimeout             time.Duration `split_words:"true"`
	AdaptorVerbose             bool          `split_words:"true"`
	AdaptorInfluxAddr          string        `split_words:"true"`
	AdaptorInfluxUsername      string        `split_words:"true"`
	AdaptorInfluxPassword      string        `split_words:"true"`
	AdaptorInfluxClientTimeout time.Duration `split_words:"true"`
	AdaptorInfluxDatabase      string        `split_words:"true"`
}

func LoadFromEnv() *Config {
	var dbconf DbConfig
	err := envconfig.Process("db", &dbconf)
	if err != nil {
		zlogger.Panic().Err(err).Msg("Error processing env")
	}
	var bizconf BizConfig
	err = envconfig.Process("biz", &bizconf)
	if err != nil {
		zlogger.Panic().Err(err).Msg("Error processing env")
	}
	return &Config{
		DbConf:  dbconf,
		BizConf: bizconf,
	}
}
