/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package dto

//go:generate go-doudou name --file $GOFILE

type QueryData struct {
	Result     interface{} `json:"result"`
	ResultType string      `json:"resultType"`
}

type QueryResponse struct {
	Data   QueryData `json:"data"`
	Status string    `json:"status"`
}
