name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test $(go list ./... | grep -v 'ddl\|mock') -coverprofile=coverage.out -covermode=atomic
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
